version: '1'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production 